# Generated by Django 4.2.16 on 2024-09-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catgory', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=201)),
                ('sect_img', models.ImageField(blank=True, upload_to='media/sections/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(default='', max_length=46)),
                ('price', models.IntegerField(default=0)),
                ('image', models.FileField(default='', upload_to='product/')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='kak')),
                ('slug_name', models.SlugField(blank=True, default='')),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('barcode_img', models.ImageField(blank=True, upload_to='image/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.category')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.sections')),
                ('seller', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('size', models.ManyToManyField(blank=True, to='Shop.size')),
            ],
        ),
    ]
